### ISSUE TITLE
Where can I get an FHIR Client ID?

### ISSUE THREAD

**Issue by aaronjohnsonwsu** [HealthDecision/react-epic-demo#1]
Hello,

I have been browsing through your project and I saw that within you credentials.js file you have two variables that need to be populated:

- FHIR_CLIENT_ID
- FHIR_REDIRECT_URI

I am interested in learning more about epic integration and was wondering how I can get my own FHIR Client ID or is it possible to get a sandbox FHIR Client ID?

Thank you!

**Comment by thebitguru** [comment]
Hi, Aaron,

Check out https://open.epic.com and https://apporchard.epic.com.  Depending on your target use case, one or the other will apply.

Good luck!
